spring.application.name=Stay_Hub

# H2 (in-memory)
spring.datasource.url=jdbc:h2:mem:stayhub;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

supplier.webclient.connect-timeout-ms=2000
supplier.webclient.response-timeout-ms=3000

# Mock Supplier
supplier.a.base-url=http://localhost:9090
supplier.a.api-key=mock-api-key-a
supplier.b.base-url=http://localhost:9090
supplier.b.api-key=mock-api-key-b